# dependency of lamb-code:
# - RabbitMQ
# - MySQL

version: '3.0'
services:

  mq:
    container_name: mq
    image: rabbitmq:management
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: go
      RABBITMQ_DEFAULT_USER: go
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - 45672:15672 # control panel

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: go
      MYSQL_DATABASE: problem
      MYSQL_USER: go
      MYSQL_PASSWORD: go
    volumes:
      - ./config/SQL:/docker-entrypoint-initdb.d

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
